name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r templates/testing/selenium/requirements.txt
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
    
    - name: Start frontend and backend
      run: |
        # This would be replaced with your actual commands to start the application
        # For example:
        # docker-compose up -d
        echo "Starting application..."
        # Placeholder for starting your application
    
    - name: Wait for application to start
      run: |
        echo "Waiting for application to start..."
        sleep 10
    
    - name: Run Selenium tests
      run: |
        cd templates/testing/selenium
        python -m unittest test_task_manager.py
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: templates/testing/selenium/test-results/
